import{a as v,S as $,i as h}from"./assets/vendor-09d7c26e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const P="43687048-bb18a09d847445a540140347b",y=15;async function m(t,a){const r=`https://pixabay.com/api/?key=${P}&q=${t}
  &image_type=photo&orientation=horizontal&safesearch=true&page=${a}&per_page=${y}`;try{const n=await v.get(r);if(n.status!==200)throw new Error("Network response was not ok");const{hits:e,totalHits:o}=n.data;return{images:e,totalImages:o}}catch(n){throw new Error(n.message)}}const H=new $(".gallery a",{captionsData:"alt",captionDelay:250});function w(){return document.querySelector(".gallery")}function L(){return document.querySelector(".loader")}function E(){return document.getElementById("load-more")}function g(t){const a=w(),r=t.map(n=>{const{largeImageURL:e,webformatURL:o,tags:s,likes:b,views:I,comments:B,downloads:M}=n;return`
      <li class="gallery-container">
        <a href="${e}" title="${s}">
          <img src="${o}" alt="${s}" class="card-img-top">
        </a>
        <div class="card-body">
          <p class="card-text"><span>Likes:</span> ${b}</p>
          <p class="card-text"><span>Views:</span> ${I}</p>
          <p class="card-text"><span>Comments:</span> ${B}</p>
          <p class="card-text"><span>Downloads:</span> ${M}</p>
        </div>
      </li>
    `});a.insertAdjacentHTML("beforeend",r.join("")),H.refresh()}function x(){const t=E();t.style.display="block"}function p(){const t=E();t.style.display="none"}function O(){const t=w();t.innerHTML=""}function f(){const t=L();t.style.display="block"}function i(){const t=L();t.style.display="none"}function l(t){h.error({title:"Error",message:t,position:"topRight"})}function S(t){h.info({title:"Info",message:t,position:"topRight"})}let c=1,u=0,d=null;document.addEventListener("DOMContentLoaded",function(){document.getElementById("search-form").addEventListener("submit",async function(r){if(r.preventDefault(),O(),d=document.getElementById("search-input").value.trim(),d!==""){p(),f();try{c=1;const{images:e,totalImages:o}=await m(d,c);i(),e.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(g(e),u=Math.ceil(o/y),u>1&&x())}catch{i(),l("An error occurred while fetching data. Please try again later.")}}else l("Please enter a search query.")}),document.getElementById("load-more").addEventListener("click",async function(){try{c+=1,f();const{images:r}=await m(d,c);g(r),i(),q(),c>=u&&(S("We're sorry, but you've reached the end of search results."),p())}catch(r){i(),l(r.message)}})});function q(){const t=document.querySelector(".gallery-container:last-child");if(t){const r=t.getBoundingClientRect().height*2;window.scrollBy({top:r,left:0,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
