import{a as M,S as v,i as f}from"./assets/vendor-09d7c26e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const $="43687048-bb18a09d847445a540140347b",h=15;async function m(t,a){const r=`https://pixabay.com/api/?key=${$}&q=${t}
  &image_type=photo&orientation=horizontal&safesearch=true&page=${a}&per_page=${h}`;try{const n=await M.get(r);if(n.status!==200)throw new Error("Network response was not ok");const{hits:e,totalHits:o}=n.data;return{images:e,totalImages:o}}catch(n){throw new Error(n.message)}}const P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(){return document.querySelector(".gallery")}function w(){return document.querySelector(".loader")}function L(){return document.getElementById("load-more")}function g(t){const a=y(),r=t.map(n=>{const{largeImageURL:e,webformatURL:o,tags:s,likes:E,views:b,comments:I,downloads:B}=n;return`
      <li class="gallery-container">
        <a href="${e}" title="${s}">
          <img src="${o}" alt="${s}" class="card-img-top">
        </a>
        <div class="card-body">
          <p class="card-text"><span>Likes:</span> ${E}</p>
          <p class="card-text"><span>Views:</span> ${b}</p>
          <p class="card-text"><span>Comments:</span> ${I}</p>
          <p class="card-text"><span>Downloads:</span> ${B}</p>
        </div>
      </li>
    `});a.insertAdjacentHTML("beforeend",r.join("")),P.refresh()}function H(){const t=L();t.style.display="block"}function x(){const t=L();t.style.display="none"}function O(){const t=y();t.innerHTML=""}function p(){const t=w();t.style.display="block"}function i(){const t=w();t.style.display="none"}function l(t){f.error({title:"Error",message:t,position:"topRight"})}function S(t){f.info({title:"Info",message:t,position:"topRight"})}let c=1,u=0,d=null;document.addEventListener("DOMContentLoaded",function(){document.getElementById("search-form").addEventListener("submit",async function(r){if(r.preventDefault(),O(),d=document.getElementById("search-input").value.trim(),d!==""){p();try{c=1;const{images:e,totalImages:o}=await m(d,c);i(),e.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(g(e),u=Math.ceil(o/h),u>1&&H())}catch{i(),l("An error occurred while fetching data. Please try again later.")}}else l("Please enter a search query.")}),document.getElementById("load-more").addEventListener("click",async function(){try{c+=1,p();const{images:r}=await m(d,c);g(r),i(),q(),c>=u&&(S("We're sorry, but you've reached the end of search results."),x())}catch(r){i(),l(r.message)}})});function q(){const t=document.querySelector(".gallery-container:last-child");if(t){const r=t.getBoundingClientRect().height*2;window.scrollBy({top:r,left:0,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
