import{a as I,S as v,i as B}from"./assets/vendor-09d7c26e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const M="43687048-bb18a09d847445a540140347b",d=15;async function u(r,a){const n=`https://pixabay.com/api/?key=${M}&q=${r}
  &image_type=photo&orientation=horizontal&safesearch=true&page=${a}&per_page=${d}`;try{const o=await I.get(n);if(console.log(o),o.status!==200)throw new Error("Network response was not ok");if(a*d>o.data.totalHits)throw new Error("We're sorry, but you've reached the end of search results.");return o.data.hits}catch(o){throw new Error(o.message)}}const $=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(){return document.querySelector(".gallery")}function h(){return document.querySelector(".loader")}function f(){return document.getElementById("load-more")}function m(r){const a=g(),n=r.map(o=>{const{largeImageURL:e,webformatURL:t,tags:s,likes:w,views:L,comments:E,downloads:b}=o;return`
      <li class="gallery-container">
        <a href="${e}" title="${s}">
          <img src="${t}" alt="${s}" class="card-img-top">
        </a>
        <div class="card-body">
          <p class="card-text"><span>Likes:</span> ${w}</p>
          <p class="card-text"><span>Views:</span> ${L}</p>
          <p class="card-text"><span>Comments:</span> ${E}</p>
          <p class="card-text"><span>Downloads:</span> ${b}</p>
        </div>
      </li>
    `});a.insertAdjacentHTML("beforeend",n.join("")),$.refresh()}function p(){const r=f();r.style.display="block"}function q(){const r=f();r.style.display="none"}function P(){const r=g();r.innerHTML=""}function y(){const r=h();r.style.display="block"}function i(){const r=h();r.style.display="none"}function c(r){B.error({title:"Error",message:r,position:"topRight"})}let l=1;document.addEventListener("DOMContentLoaded",function(){document.getElementById("search-form").addEventListener("submit",async function(n){n.preventDefault(),P();const e=document.getElementById("search-input").value.trim();if(e!==""){y();try{l=1;const t=await u(e,l);i(),t.length===0?c("Sorry, there are no images matching your search query. Please try again!"):(m(t),p())}catch{i(),c("An error occurred while fetching data. Please try again later.")}}else c("Please enter a search query.")}),document.getElementById("load-more").addEventListener("click",async function(n){n.preventDefault();const e=document.getElementById("search-input").value.trim();if(e!==""){q(),y();try{l+=1;const t=await u(e,l);i(),t.length===0?c("Sorry, there are no images matching your search query. Please try again!"):(m(t),p(),H())}catch(t){i(),c(t.message)}}else c("Please enter a search query.")})});function H(){const r=document.querySelector(".gallery-container:last-child");if(r){const n=r.getBoundingClientRect().height*2;window.scrollBy({top:n,left:0,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
